### ISSUE TITLE
Question about "No of weeks needed to observe sheep" is not answered in "Foot and mouth disease analysis"

### ISSUE THREAD

**Issue by JagaRamesh** [dantesolo/intro-data-capstone-biodiversity#1]
The following questions were not addressed in "Foot and mouth disease analysis"
1. How many weeks would you need to observe sheep at Bryce National Park in order to observe enough sheep? 
2. How many weeks would you need to observe at Yellowstone National Park to observe enough sheep?

With the sample size of 520, 
bryce = 510 / 250.
yellowstone = 510 / 507.
Approximately 2 weeks are needed at Bryce and 1 week at Yellowstone.

**Comment by dave-melillo** [comment]
Thank you for the review Jaga! Maybe I am missing something but I thought I answered those questions on line 405-409 in the .py file ...They are at the very bottom ...

bryce = 510 / 250.
yellowstone = 510 / 507.

# Approximately 2 weeks at Bryce and 1 week at Yellowstone.

**Comment by JagaRamesh** [comment]
Yes. It is in the script but not in the powerpoint slides.

**Comment by dave-melillo** [comment]
Thank you! Fixed
