### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [dantesolo/intro-data-capstone-biodiversity#2]
Overall Excellent work! Accurate coding!

The matplotlib plots in the appendix section are neat with proper title, xlabel and ylabel defined. It would be good to capture those plots in the main slides

Few recommendations on powerpoint:
1. Start the powerpoint with the "Objective" slide for each of the analysis.
2. Highlight the analysis using charts/plots and summarize your findings in bullet points in the slides.

The conclusion and recommendation is accurate for "Endangerment of species" analysis.
For "Foot and mouth disease analysis", the question about "No of weeks needed to observe sheep" is not answered. I have created an issue for the same.

Great job! KEEP IT UP!!

**Comment by dave-melillo** [comment]
Jaga - I believe I answered those questions previously. Maybe I am missing something? I commented in the sub issue, let me know if I am misunderstanding something. Thank you again.
